apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # deployment labels
  labels:
    component: catalogue  
    project: roboshop 
    tier: app
spec:
  replicas: 1
# These are the labels replica set use to create pod replicas, This should match pod labels.
  selector:
    matchLabels:
      component: catalogue  
      project: roboshop 
      tier: app
  template:
  # This pod defination
    metadata:
      labels:
        component: catalogue  
        project: roboshop 
        tier: app
    spec:
      containers:
      - name: catalogue
        image: "{{ .Values.deployment.imageUrl }}:{{ .Values.deployment.imageVersion }}"
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
           name: catalogue